sequelize-stallions/horse-puns

package.json

changed json name

---

package.json

added description in Package JSON

---

README.md

added some tasks

---

server/db/models/user.js

user model

---

package-lock.json
server/api/products.js

Getproducts#9

---

package-lock.json
server/api/products.js

Getproduct#10

---

server/db/models/product.js
server/db/models/user.js

product model

---

server/db/models/cart.js
server/db/models/index.js

cart model

---

server/db/models/cart.js
server/db/models/index.js

Models assosiation

---

server/db/models/index.js

fixed association with through

---

.idea/workspace.xml
client/components/AllProducts.js
client/components/navbar.js
client/routes.js
client/store/allProducts.js
client/store/index.js
public/index.html

Added listComponent

---

client/components/single-product.js
client/store/index.js
client/store/products.js

Association fix

---

client/components/AllProducts.js

added name and stuff

---

client/components/SingleProduct.js

Single Product page basic functionality

---

client/routes.js
server/api/products.js

single product page WORKING

---

client/components/AllProducts.js
client/components/SingleProduct.js

added commas to price display

---

client/index.js
server/db/models/user.js

Google Sign in and up working

---

client/components/cart.js
client/components/navbar.js
client/routes.js

basic cart component

---

script/seed.js

fixed(test spec seed file)

---

server/api/products.spec.js

created test spec for product route

---

server/db/models/index.js
server/db/models/product.js
server/db/models/product_cart.js

added(new model ProductCart), fixed (association issues)

---

client/components/user-home.js
server/api/carts.js
server/api/index.js
server/db/models/cart.js

made findOrCreate cart route for loggedin user

---

server/db/models/product.spec.js

made test spec for product model

---

client/components/cart.js
client/components/user-home.js
client/store/cart.js
client/store/index.js
server/api/carts.js

feat(cart reducer): added check cart and get cart actions

---

.travis.yml

connected travis and loaded database to heroku

---

client/components/SingleProduct.js
client/components/cart.js
client/store/cart.js
server/api/carts.js
server/db/models/product_cart.js

Add remove

---

client/components/user-home.js

(fix)deleted mapStateProps import that broke our test functionality

---

client/components/navbar.js
client/store/cart.js

feat(cart): cart is cleared when user logs out

---

client/components/checkout.js
client/routes.js

feat(react): added checkout component

---

client/components/cart.js
client/store/cart.js
server/api/carts.js

feat(cart): checkout changes order status but does not create new cart

---

client/components/checkout.js

fix(react): added redirection to home page after checkout

---

client/components/cart.js
client/components/checkout.js
client/components/user-home.js
client/store/cart.js
script/seed.js
server/api/carts.js

fix(cart): new cart is created and loaded on checkout

---

.travis.yml

fixed the heroku token

---

client/components/user-home.js
client/components/user-home.spec.js

fix(user-home test): added dummy functions to help the test run fully

---

server/auth/index.js

feat(cart): new cart is created on signup

---

client/components/user-home.spec.js
server/api/products.spec.js
server/db/models/product.spec.js
server/db/models/user.spec.js

feat(product-model-tests): added 4 tests

---

client/components/user-home.spec.js
server/api/products.spec.js
server/db/models/user.spec.js

fix(tests): activated some inactive tests

---

server/api/products.spec.js

Fix(test): fixed products.spec.js on api/routes folder

---

client/store/cart.js

fix(test): travis rebuild test

---

server/api/products.spec.js
server/db/models/cart.spec.js
server/db/models/index.js
server/db/models/product_cart.spec.js
server/db/models/user.js
server/db/models/user.spec.js

New tests back end

---

client/components/user-home.js
client/components/user-home.spec.js
script/seed.spec.js

fix(seed.spec): fixed seed.spec file and fixed user-home.spec

---

server/auth/google.js

fix(google): cart is created on google signup if new user

---

client/components/user-home.spec.js

fix(user-home.spec): added props

---

client/components/navbar.js
client/components/user-home.js

fix(guest-cart): local cart clears on sign in

---

client/components/navbar.js

fix(guest-cart): fixed initial local storage

---

client/components/navbar.js

fix(localStorage): changed check for localStorage
